### ISSUE TITLE
Build error when add CodingSebLocalization

### ISSUE THREAD

**Issue by linhmc** [codingseb/Localization#3]
Hi @codingseb,
When I add  
`<CodingSebLocalization />`
to FodyWeavers.xml file.
I always get this error when rebuilding project
![image](https://user-images.githubusercontent.com/20184892/149864015-5a5fe656-10cf-4c9e-a085-65c5553c3a01.png)

Please help me to check this error.
Thank You.

**Comment by codingseb** [comment]
Hello @linhmc.
This is due to missing dependencies for the fody weaver when used by nuget.
I published version 1.2.0 to correct it.
Just take in account that some version of .net framework are now not supported anymore.
You need at least framework 4.6.2 or .net core 3.1

If you want to make it work at the current version you can try to copy in "%userprofile%\.nuget\packages\codingseblocalization.fody\your version\weaver" : 
* __CodingSeb.Localization.dll__ from your output directory
* __System.ObjectModel.dll__ from the following zipfile or from your system "%userprofile%\.nuget\packages\system.objectmodel\an available version\lib\netstandard1.3"
* __System.Runtime.dll__ rom the following zipfile or from your system "%userprofile%\.nuget\packages\system.objectmodel\an available version\lib\search in dirs"

__[weaver.zip](https://github.com/codingseb/Localization/files/7903254/weaver.zip)__

**Comment by linhmc** [comment]
Hello @codingseb.
Thank you for your help.
